# Utiliser une image de base Python
FROM python:3.9-slim

# Définir le répertoire de travail dans l'image
WORKDIR /app

# Copier les fichiers de l'application dans l'image
COPY . .

# Installer les dépendances Python
RUN pip install -r requirements.txt

# Exposer le port sur lequel l'application Flask écoute
EXPOSE 5000

# Commande pour démarrer l'application
CMD ["python", "app.py"]
